- name: Set up automatic codesigning
  script: |
    keychain initialize
    app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

    keychain add-certificates
    xcode-project use-profiles
