workflows:
  ios_to_testflight:
    name: iOS → TestFlight
    environment:
      xcode: 16.4
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"   # <- change if your .xcodeproj name differs
        XCODE_SCHEME: "HelloWorld"              # <- must match an Xcode shared scheme
        BUNDLE_ID: "au.gbaz.app"                # <- your bundle id (must match the profile)
    scripts:
      # Use your uploaded .p12 + .mobileprovision and switch project to MANUAL signing
      - name: Prepare signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      # (Optional but helpful) Quick sanity check
      - name: Verify build settings
        script: |
          xcodebuild -list -project "$XCODE_PROJECT" || true
          xcodebuild -showBuildSettings \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release 2>/dev/null | \
            egrep "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER" || true

      # Build + archive + export IPA for App Store
      - name: Build IPA
        script: |
          set -o pipefail
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-method app-store \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - $HOME/Library/Logs/gym/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # beta_groups:
        #   - "External Testers"
