workflows:
  ios_to_testflight:
    name: iOS → TestFlight

    integrations:
      app_store_connect: "gbaz 15/9"

    environment:
      xcode: 16.4
      groups: [gbaz]
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"   # change if your .xcodeproj name differs
        XCODE_SCHEME: "HelloWorld"             # change if your scheme name differs
        BUNDLE_ID: "au.gbaz.app"

    scripts:
      - name: Codesign (ASC)
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Ensure Info.plist (create if missing) + keys
        script: |
          set -e
          PLIST="IOS-FirstApp/Info.plist"
          mkdir -p "$(dirname "$PLIST")"
          if [ ! -f "$PLIST" ]; then
            cat > "$PLIST" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleDisplayName</key><string>HelloWorld</string>
  <key>CFBundleIdentifier</key><string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>UIMainStoryboardFile</key><string>Main</string>
  <key>UILaunchStoryboardName</key><string>LaunchScreen</string>
</dict></plist>
PLIST
          fi
          ensure() { /usr/libexec/PlistBuddy -c "Set :$1 $2" "$PLIST" 2>/dev/null || /usr/libexec/PlistBuddy -c "Add :$1 string $2" "$PLIST"; }
          ensure UIMainStoryboardFile Main
          ensure UILaunchStoryboardName LaunchScreen
          ensure NSLocationWhenInUseUsageDescription "We use your location to place discoveries on the map."
          ensure NSMicrophoneUsageDescription "Microphone is used for audio features and keyword detection."
          ensure NSSpeechRecognitionUsageDescription "Speech recognition is used to detect the 'reward' keyword."

      - name: Auto-bump build number
        script: |
          set -e
          PLIST="IOS-FirstApp/Info.plist"
          NEW_BUILD=$(date +%Y%m%d%H%M)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEW_BUILD" "$PLIST"
          echo "Set CFBundleVersion to $NEW_BUILD in $PLIST"

      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

    artifacts:
      - "$CM_BUILD_DIR/*.ipa"
      - "$CM_BUILD_DIR/app.xcarchive"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
