workflows:
  ios_to_testflight:
    name: iOS → TestFlight

    integrations:
      app_store_connect: "gbaz 15/9"

    environment:
      xcode: 16.4
      groups: [gbaz]
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"
        XCODE_SCHEME: "HelloWorld"
        BUNDLE_ID: "au.gbaz.app"

    scripts:
      - name: Codesign (ASC)
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Merge + heal asset catalog
        script: |
          set -e
          CANON="HelloWorld/Assets.xcassets"
          ROOT_JSON="$CANON/Contents.json"
          APPICON="$CANON/AppIcon.appiconset"

          # Merge any stray catalogs into canonical, then remove strays
          mkdir -p "$CANON"
          if [ -d assets.xcassets ]; then
            cp -R assets.xcassets/. "$CANON/" || true
            rm -rf assets.xcassets
          fi
          if [ -d helloworld/assets.xcassets ]; then
            cp -R helloworld/assets.xcassets/. "$CANON/" || true
            rm -rf helloworld/assets.xcassets
          fi

          # If AppIcon path exists but isn't a dir, back it up
          if [ -e "$APPICON" ] && [ ! -d "$APPICON" ]; then
            TS=$(date +%s)
            mv -f "$APPICON" "${APPICON}.bak.$TS"
          fi

          # Fix casing inside
          [ -d "$CANON/appicon.appiconset" ] && mv -f "$CANON/appicon.appiconset" "$APPICON"
          mkdir -p "$APPICON"
          [ -f "$APPICON/contents.json" ] && mv -f "$APPICON/contents.json" "$APPICON/Contents.json"

          # Ensure root Contents.json
          if [ ! -f "$ROOT_JSON" ] || ! plutil -lint "$ROOT_JSON" >/dev/null 2>&1; then
            printf '%s\n' '{ "info": { "version": 1, "author": "xcode" } }' > "$ROOT_JSON"
          fi

          # Minimal valid AppIcon if missing/invalid
          if [ ! -f "$APPICON/Contents.json" ] || ! plutil -lint "$APPICON/Contents.json" >/dev/null 2>&1; then
            printf '%s\n' '{ "images":[{"idiom":"ios-marketing","size":"1024x1024","scale":"1x","filename":"AppIcon-1024.png"}], "info":{"version":1,"author":"xcode"} }' > "$APPICON/Contents.json"
          fi
          if [ ! -f "$APPICON/AppIcon-1024.png" ]; then
            /usr/bin/sips -s format png --resampleHeightWidth 1024 1024 \
              /System/Library/CoreServices/DefaultDesktop.jpg \
              --out "$APPICON/AppIcon-1024.png" >/dev/null 2>&1 || true
          fi

          echo "=== Assets tree ==="
          find "$CANON" -maxdepth 2 -print || true
          echo "=== Lint ==="
          plutil -lint "$ROOT_JSON" "$APPICON/Contents.json" || true

      - name: Build IPA
        script: |
          set -e
          # Optional: keep min iOS in sync
          /usr/bin/sed -i '' -E 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' HelloWorld.xcodeproj/project.pbxproj || true
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

    artifacts:
      - "$CM_BUILD_DIR/*.ipa"
      - "$CM_BUILD_DIR/app.xcarchive"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

