workflows:
  ios_to_testflight:
    name: iOS → TestFlight
    integrations:
      app_store_connect: "gbaz 15/9"
    environment:
      xcode: 16.4
      groups: [gbaz]
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"
        XCODE_SCHEME: "HelloWorld"
        BUNDLE_ID: "au.gbaz.app"
    scripts:
      - name: Codesign
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: |
          set -e
          if ls *.xcworkspace >/dev/null 2>&1; then
            WS="$(ls -1 *.xcworkspace | head -n1)"
            xcode-project build-ipa --workspace "$WS" --scheme "$XCODE_SCHEME"
          else
            xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
          fi
          mkdir -p build/ios/ipa
          IPA="$(find "$CM_BUILD_DIR" -type f -name '*.ipa' -print -quit)"
          [ -n "$IPA" ] && cp -f "$IPA" build/ios/ipa/HelloWorld.ipa
    artifacts:
      - build/ios/ipa/HelloWorld.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
