workflows:
  ios_release:
    name: iOS Release to TestFlight
    integrations:
      app_store_connect: gbaz-asc   # ASC integration name in Codemagic
    environment:
      xcode: 16.4
      vars:
        APP_SCHEME: "HelloWorld"
        PROJECT_PATH: "HelloWorld.xcodeproj"
        BUNDLE_ID: "au.gbaz.app"
    scripts:
      - name: Show Xcode project details
        script: |
          xcodebuild -list -project "$PROJECT_PATH" || true
            - name: Increment build number (auto-detect)
        script: |
          set -euo pipefail
          echo "PROJECT_PATH=$PROJECT_PATH"
          echo "APP_SCHEME=$APP_SCHEME"
          echo "BUILD_NUMBER=${BUILD_NUMBER:-1}"

          # Try Release first, then Debug
          for CONFIG in Release Debug; do
            OUT="$(xcodebuild -showBuildSettings -project "$PROJECT_PATH" -scheme "$APP_SCHEME" -configuration "$CONFIG" 2>/dev/null || true)"
            INFOPLIST_PATH="$(echo "$OUT" | awk -F'= ' '/INFOPLIST_FILE|INFOPLIST_PATH/ {print $2; exit}')"
            SRCROOT="$(echo "$OUT" | awk -F'= ' '/ SRCROOT / {print $2; exit}')"
            if [ -n "${INFOPLIST_PATH:-}" ] && [ -n "${SRCROOT:-}" ]; then
              PLIST_PATH="$SRCROOT/$INFOPLIST_PATH"
              break
            fi
          done

          if [ -z "${PLIST_PATH:-}" ] || [ ! -f "$PLIST_PATH" ]; then
            echo "❌ Could not locate Info.plist via xcodebuild."
            echo "Tip: ensure scheme '$APP_SCHEME' is Shared and PROJECT_PATH is correct."
            exit 1
          fi

          echo "✅ Using Info.plist: $PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NUMBER:-1}" "$PLIST_PATH" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${BUILD_NUMBER:-1}" "$PLIST_PATH"
          echo "✅ CFBundleVersion -> ${BUILD_NUMBER:-1}"
      - name: Build archive
        script: |
          xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "$APP_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/app.xcarchive" \
            clean archive
      - name: Export IPA
        script: |
          cat > /tmp/exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/app.xcarchive" \
            -exportOptionsPlist /tmp/exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/Export"
    artifacts:
      - $CM_BUILD_DIR/Export/*.ipa
      - $CM_BUILD_DIR/app.xcarchive/dSYMs/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "gbaz-testers"   # <-- must match a TestFlight group name in App Store Connect
