workflows:
  ios_to_testflight:
    name: iOS → TestFlight
    integrations:
      app_store_connect: "gbaz-asc"   # <- EXACT name of your ASC integration in Codemagic
    environment:
      xcode: 16.4
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"
        XCODE_SCHEME: "HelloWorld"
        BUNDLE_ID: "au.gbaz.app"
    scripts:
      - name: Prepare signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Verify build settings
        script: |
          xcodebuild -list -project "$XCODE_PROJECT" || true
          xcodebuild -showBuildSettings \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release 2>/dev/null | \
            egrep "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER" || true

      - name: Build IPA
        script: |
          set -o pipefail
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-method app-store \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - $HOME/Library/Logs/gym/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
