workflows:
  ios_to_testflight:
    name: iOS → TestFlight

    integrations:
      app_store_connect: "gbaz 15/9"

    environment:
      xcode: 16.4
      groups: [gbaz]
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"
        XCODE_SCHEME: "HelloWorld"
        BUNDLE_ID: "au.gbaz.app"

    scripts:
      - name: Codesign (ASC)
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Merge + heal asset catalog (robust)
        script: |
          set -e
          CANON="HelloWorld/Assets.xcassets"
          ROOT_JSON="$CANON/Contents.json"
          APPICON="$CANON/AppIcon.appiconset"

          echo "=== Pre-check ==="
          ls -ld "HelloWorld" 2>/dev/null || true
          ls -ld "$CANON" 2>/dev/null || true

          # If canonical path exists as a file, back it up first, then create dir
          if [ -e "$CANON" ] && [ ! -d "$CANON" ]; then
            TS=$(date +%s)
            echo "Found file at $CANON → backing up to ${CANON}.bak.$TS"
            mv -f "$CANON" "${CANON}.bak.$TS"
          fi
          mkdir -p "$CANON"

          # Merge any stray catalogs into canonical, then remove strays
          for SRC in assets.xcassets helloworld/assets.xcassets HelloWorld/assets.xcassets Assets.xcassets; do
            if [ -d "$SRC" ] && [ "$SRC" != "$CANON" ]; then
              echo "Merging $SRC → $CANON"
              cp -R "$SRC/." "$CANON/" || true
              rm -rf "$SRC"
            fi
          done

          # If AppIcon path exists as a file, back it up
              # and normalize lowercase folder/file names
          if [ -e "$APPICON" ] && [ ! -d "$APPICON" ]; then
            TS=$(date +%s)
            echo "Found file at $APPICON → backing up to ${APPICON}.bak.$TS"
            mv -f "$APPICON" "${APPICON}.bak.$TS"
          fi
          if [ -d "$CANON/appicon.appiconset" ] && [ ! -d "$APPICON" ]; then
            mv -f "$CANON/appicon.appiconset" "$APPICON"
          fi
          mkdir -p "$APPICON"
          if [ -f "$APPICON/contents.json" ] && [ ! -f "$APPICON/Contents.json" ]; then
            mv -f "$APPICON/contents.json" "$APPICON/Contents.json"
          fi

          # Ensure root Contents.json (actool reads tags from here)
          if [ ! -f "$ROOT_JSON" ] || ! plutil -lint "$ROOT_JSON" >/dev/null 2>&1; then
            printf '%s\n' '{ "info": { "version": 1, "author": "xcode" } }' > "$ROOT_JSON"
          fi

          # Ensure AppIcon set is valid and has a 1024 icon
          if [ ! -f "$APPICON/Contents.json" ] || ! plutil -lint "$APPICON/Contents.json" >/dev/null 2>&1; then
            printf '%s\n' '{ "images":[{"idiom":"ios-marketing","size":"1024x1024","scale":"1x","filename":"AppIcon-1024.png"}], "info":{"version":1,"author":"xcode"} }' > "$APPICON/Contents.json"
          fi
          if [ ! -f "$APPICON/AppIcon-1024.png" ]; then
            /usr/bin/sips -s format png --resampleHeightWidth 1024 1024 \
              /System/Library/CoreServices/DefaultDesktop.jpg \
              --out "$APPICON/AppIcon-1024.png" >/dev/null 2>&1 || true
          fi

          echo "=== Assets tree ==="
          find "$CANON" -maxdepth 2 -print || true
          echo "=== Lint ==="
          plutil -lint "$ROOT_JSON" "$APPICON/Contents.json" || true

      - name: Normalize project refs (assets + AppIcon + min iOS)
        script: |
          set -e
          PBX="HelloWorld.xcodeproj/project.pbxproj"
          # Adjust PBX if your .xcodeproj lives elsewhere

          /usr/bin/sed -i '' -E 's/assets\.xcassets/Assets.xcassets/g' "$PBX" || true
          /usr/bin/sed -i '' -E 's/appicon\.appiconset/AppIcon.appiconset/g' "$PBX" || true
          /usr/bin/sed -i '' -E 's/ASSETCATALOG_COMPILER_APPICON_NAME = [^;]*/ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon/' "$PBX" || true
          /usr/bin/sed -i '' -E 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+/IPHONEOS_DEPLOYMENT_TARGET = 12.0/' "$PBX" || true

          echo "=== pbxproj matches ==="
          /usr/bin/grep -n "Assets.xcassets\|AppIcon" "$PBX" || true

      - name: Ensure Info.plist usage descriptions
        script: |
          set -e
          PLIST="HelloWorld/Info.plist"
          ensure() { /usr/libexec/PlistBuddy -c "Set :$1 $2" "$PLIST" 2>/dev/null || /usr/libexec/PlistBuddy -c "Add :$1 string $2" "$PLIST"; }
          ensure UIMainStoryboardFile "Main"
          ensure UILaunchStoryboardName "LaunchScreen"
          ensure NSMicrophoneUsageDescription "Needed for sound recognition."
          ensure NSLocationWhenInUseUsageDescription "Needed to place discoveries on the Sydney CBD map."

      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

    artifacts:
      - "$CM_BUILD_DIR/*.ipa"
      - "$CM_BUILD_DIR/app.xcarchive"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

