workflows:
  ios_to_testflight:
    name: iOS → TestFlight
    integrations:
      app_store_connect: "gbaz-asc"   # <- must match your integration name in Codemagic
    environment:
      xcode: 16.4
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"
        XCODE_SCHEME: "HelloWorld"
        BUNDLE_ID: "au.gbaz.app"
    scripts:
      - name: Prepare signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Force Swift 5.0
        script: |
          echo "Patching Swift version to 5.0..."
          sed -i '' 's/SWIFT_VERSION = 3.0/SWIFT_VERSION = 5.0/g' "$XCODE_PROJECT/project.pbxproj"

      - name: Build archive
        script: |
          set -o pipefail
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            clean archive | xcpretty

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/app.xcarchive
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - $HOME/Library/Logs/gym/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
