workflows:
  ios_to_testflight:
    name: iOS → TestFlight

    integrations:
      app_store_connect: "gbaz 15/9"

    environment:
      xcode: 16.4
      groups: [gbaz]
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"
        XCODE_SCHEME: "HelloWorld"
        BUNDLE_ID: "au.gbaz.app"

    scripts:
      - name: Codesign (ASC)
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Ensure Info.plist + keys
        script: |
          set -e
          PLIST="IOS-FirstApp/Info.plist"
          mkdir -p "$(dirname "$PLIST")"
          [ -f "$PLIST" ] || printf '%s' '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict/></plist>' > "$PLIST"
          ensure() { /usr/libexec/PlistBuddy -c "Set :$1 \"$2\"" "$PLIST" 2>/dev/null || /usr/libexec/PlistBuddy -c "Add :$1 string \"$2\"" "$PLIST"; }
          ensure UIMainStoryboardFile Main
          ensure UILaunchStoryboardName LaunchScreen
          ensure NSLocationWhenInUseUsageDescription 'We use your location to place discoveries on the map.'
          ensure NSMicrophoneUsageDescription 'Microphone is used for audio features.'
          ensure NSSpeechRecognitionUsageDescription 'Speech recognition is used for keyword detection.'
          plutil -lint "$PLIST"

      - name: Auto-bump build number
        script: |
          set -e
          PLIST="IOS-FirstApp/Info.plist"
          NEW_BUILD=$(date +%Y%m%d%H%M)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEW_BUILD" "$PLIST"

      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/HelloWorld.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
