workflows:
  ios_release:
    name: iOS Release to TestFlight
    integrations:
      app_store_connect: gbaz-asc   # ASC integration name in Codemagic
    environment:
      xcode: 16.4
      vars:
        APP_SCHEME: "HelloWorld"
        PROJECT_PATH: "HelloWorld.xcodeproj"
        BUNDLE_ID: "au.gbaz.app"
    scripts:
      - name: Show Xcode project details
        script: |
          xcodebuild -list -project "$PROJECT_PATH" || true
      - name: Increment build number
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" \
            "$PROJECT_PATH/../HelloWorld/Info.plist"
      - name: Build archive
        script: |
          xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "$APP_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/app.xcarchive" \
            clean archive
      - name: Export IPA
        script: |
          cat > /tmp/exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/app.xcarchive" \
            -exportOptionsPlist /tmp/exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/Export"
    artifacts:
      - $CM_BUILD_DIR/Export/*.ipa
      - $CM_BUILD_DIR/app.xcarchive/dSYMs/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "gbaz-testers"   # <-- must match a TestFlight group name in App Store Connect
