workflows:
  ios_to_testflight:
    name: iOS → TestFlight
    integrations:
      app_store_connect: "gbaz 15/9"
    environment:
      xcode: 16.4
      groups: [gbaz]
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"
        XCODE_SCHEME: "HelloWorld"
        BUNDLE_ID: "au.gbaz.app"
    scripts:
      - name: Codesign
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Info.plist
        script: |
          set -e
          PLIST="IOS-FirstApp/Info.plist"; mkdir -p "$(dirname "$PLIST")"
          [ -f "$PLIST" ] || printf '%s' '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict/></plist>' > "$PLIST"
          ensure(){ /usr/libexec/PlistBuddy -c "Set :$1 \"$2\"" "$PLIST" 2>/dev/null || /usr/libexec/PlistBuddy -c "Add :$1 string \"$2\"" "$PLIST"; }
          ensure UIMainStoryboardFile Main
          ensure UILaunchStoryboardName LaunchScreen
          ensure NSLocationWhenInUseUsageDescription "We use your location to place discoveries on the map."
      - name: iOS 12 + Assets
        script: |
          set -e
          PBX="HelloWorld.xcodeproj/project.pbxproj"
          /usr/bin/sed -i '' -E 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]+(\.[0-9]+)?/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' "$PBX" || true
          /usr/bin/sed -i '' 's|HelloWorld/Assets\.xcassets|assets.xcassets|g' "$PBX" || true
          /usr/bin/sed -i '' 's/ASSETCATALOG_COMPILER_APPICON_NAME = [^;]*/ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon/' "$PBX" || true
          CATALOG="assets.xcassets"; APPICON="$CATALOG/AppIcon.appiconset"
          [ -d "$CATALOG" ] || mkdir -p "$CATALOG"
          [ -f "$CATALOG/Contents.json" ] || printf '%s\n' '{ "info": { "version": 1, "author": "xcode" } }' > "$CATALOG/Contents.json"
          [ -d "$APPICON" ] || mkdir -p "$APPICON"
          [ -f "$APPICON/Contents.json" ] || printf '%s\n' '{ "images":[{"idiom":"ios-marketing","size":"1024x1024","scale":"1x","filename":"AppIcon-1024.png"}], "info":{"version":1,"author":"xcode"} }' > "$APPICON/Contents.json"
          [ -f "$APPICON/AppIcon-1024.png" ] || /usr/bin/sips -s format png --resampleHeightWidth 1024 1024 /System/Library/CoreServices/DefaultDesktop.jpg --out "$APPICON/AppIcon-1024.png" >/dev/null 2>&1 || true
      - name: Fix storyboards (force minimal XML)
        script: |
          set -e
          mkdir -p HelloWorld/Base.lproj
          MAIN="HelloWorld/Base.lproj/Main.storyboard"
          LAUNCH="HelloWorld/Base.lproj/LaunchScreen.storyboard"
          printf '%s' '<?xml version="1.0" encoding="UTF-8"?><document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard" version="3.0" toolsVersion="20037" targetRuntime="iOS.CocoaTouch" initialViewController="nav"><scenes><scene sceneID="s1"><objects><navigationController id="nav" sceneMemberID="viewController"><connections><segue destination="root" kind="relationship" relationship="rootViewController" id="rel1"/></connections></navigationController><placeholder placeholderIdentifier="IBFirstResponder" id="p1" sceneMemberID="firstResponder"/></objects></scene><scene sceneID="s2"><objects><viewController id="root" sceneMemberID="viewController"><view key="view" contentMode="scaleToFill" id="v1"><rect key="frame" x="0" y="0" width="390" height="844"/><autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/><color key="backgroundColor" white="1" alpha="1" colorSpace="calibratedWhite"/></view></viewController><placeholder placeholderIdentifier="IBFirstResponder" id="p2" sceneMemberID="firstResponder"/></objects></scene></scenes></document>' > "$MAIN"
          printf '%s' '<?xml version="1.0" encoding="UTF-8"?><document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard" version="3.0" toolsVersion="20037" targetRuntime="iOS.CocoaTouch" launchScreen="YES"><scenes><scene sceneID="l1"><objects><viewController id="lvc" sceneMemberID="viewController"><view key="view" contentMode="scaleToFill" id="lv1"><rect key="frame" x="0" y="0" width="390" height="844"/><autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/><color key="backgroundColor" white="1" alpha="1" colorSpace="calibratedWhite"/></view></viewController><placeholder placeholderIdentifier="IBFirstResponder" id="lp1" sceneMemberID="firstResponder"/></objects></scene></scenes></document>' > "$LAUNCH"
          /Applications/Xcode-16.4.app/Contents/Developer/usr/bin/ibtool --compile /tmp/Main.cib "$MAIN"
          /Applications/Xcode-16.4.app/Contents/Developer/usr/bin/ibtool --compile /tmp/Launch.cib "$LAUNCH"
      - name: Build IPA (workspace or project)
        script: |
          set -e
          if ls *.xcworkspace >/dev/null 2>&1; then
            WS="$(ls -1 *.xcworkspace | head -n1)"
            xcode-project build-ipa --workspace "$WS" --scheme "$XCODE_SCHEME"
          else
            xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
          fi
          mkdir -p build/ios/ipa
          IPA_SRC=$(find "$CM_BUILD_DIR" -type f -name "*.ipa" | head -n1 || true)
          [ -n "$IPA_SRC" ] && cp -f "$IPA_SRC" build/ios/ipa/HelloWorld.ipa || true
    artifacts:
      - build/ios/ipa/HelloWorld.ipa
      - "$CM_BUILD_DIR/*.ipa"
      - "$CM_BUILD_DIR/app.xcarchive"
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
