workflows:
  ios_release:
    name: iOS Release to TestFlight
    integrations:
      app_store_connect: gbaz-asc   # must match the integration name you set in Codemagic
    environment:
      xcode: 16.4
      vars:
        APP_SCHEME: "HelloWorld"
        PROJECT_PATH: "HelloWorld.xcodeproj"
        BUNDLE_ID: "au.gbaz.app"
    scripts:
      - name: Show Xcode project details
        script: |
          xcodebuild -list -project "$PROJECT_PATH" || true

      - name: Locate & bump build number
        script: |
          set -euo pipefail
          echo "Looking for Info.plist with CFBundleIdentifier=$BUNDLE_ID"

          # Find the Info.plist that matches your bundle id
          PLIST_PATH=""
          while IFS= read -r -d '' P; do
            ID=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$P" 2>/dev/null || true)
            if [ "$ID" = "$BUNDLE_ID" ]; then
              PLIST_PATH="$P"
              break
            fi
          done < <(find . -type f -name Info.plist -print0)

          if [ -z "$PLIST_PATH" ]; then
            echo "❌ No Info.plist found with CFBundleIdentifier=$BUNDLE_ID"
            exit 1
          fi

          echo "✅ Found Info.plist: $PLIST_PATH"

          # Ensure version keys exist
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 1.0.0" "$PLIST_PATH" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string 1" "$PLIST_PATH" 2>/dev/null || true

          # Bump build number to Codemagic's $BUILD_NUMBER
          : "${BUILD_NUMBER:=1}"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$PLIST_PATH" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUMBER" "$PLIST_PATH"

          echo "✅ CFBundleVersion -> $BUILD_NUMBER at $PLIST_PATH"

      - name: Build archive
        script: |
          xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "$APP_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/app.xcarchive" \
            clean archive

      - name: Export IPA
        script: |
          cat > /tmp/exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/app.xcarchive" \
            -exportOptionsPlist /tmp/exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/Export"

    artifacts:
      - $CM_BUILD_DIR/Export/*.ipa
      - $CM_BUILD_DIR/app.xcarchive/dSYMs/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "gbaz-testers"   # must match your TestFlight group name in App Store Connect
