workflows:
  ios_to_testflight:
    name: iOS → TestFlight

    # (optional) keep this — it helps you see which integration the workflow expects in the UI
    integrations:
      app_store_connect: "gbaz 15/9"

    environment:
      xcode: 16.4
      vars:
        XCODE_PROJECT: "HelloWorld.xcodeproj"
        XCODE_SCHEME: "HelloWorld"
        BUNDLE_ID: "au.gbaz.app"
        # TEAM_ID not needed when using Codemagic's profiles helper
        # TEAM_ID: "8WPD9W2B39"

    scripts:
      # 1) Fetch/create signing files and import to keychain
      - name: Fetch signing files from App Store Connect
        script: |
          set -e
          # Creates or fetches a Distribution certificate + App Store profile for your BUNDLE_ID
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          # Initialize the build keychain and import downloaded certs
          keychain initialize
          keychain add-certificates
          # Make Xcode use the downloaded provisioning profiles automatically
          xcode-project use-profiles

      # 2) (Optional) Auto-detect scheme if your scheme name changes
      - name: Ensure scheme (auto-detect if missing)
        script: |
          set -e
          echo "=== Schemes ==="
          xcodebuild -list -project "$XCODE_PROJECT" || true
          if ! xcodebuild -list -project "$XCODE_PROJECT" | grep -q "^\s*$XCODE_SCHEME$"; then
            DETECTED_SCHEME=$(xcodebuild -list -project "$XCODE_PROJECT" | awk '/Schemes:/{p=1;next} p&&NF{print $0} !NF&&p{exit}' | head -n1 | sed 's/^[[:space:]]*//')
            echo "Using detected scheme: $DETECTED_SCHEME"
            echo "export XCODE_SCHEME=\"$DETECTED_SCHEME\"" >> $CM_ENV
          fi

      # 3) Build + export IPA (Codemagic helper handles ExportOptionsPlist)
      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/app.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        integration: "gbaz 15/9"   # << ADD THIS (exact name from Integrations)
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
